### PR TITLE
Add navigation feature

### PR DESCRIPTION
**Pull request by jrosario19**
## Add the following feature with my partner (shingiebhengesa@gmail.com):
- Add nav-bar.
- Add CSS selector to hide and show elements on a single page.

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @jrosario19 & @ShingiraiBhengesa👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- The Awesome book's application has a Navigation bar, Books list, Add book form and Contact info.✔️
- Application functions properly.✔️
- All links work correctly.✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!



# Required Changes ♻️
_**Your README is unavailable for inline reviews**_
- [x] **Required:** As this is a group project, it is professional to have the authors' information documented on the README.
- [x] **Optional:** Your live demo isn't working, fix it if you can.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jrosario19** [comment]
@brytebee Thank you very much for your response, but we have one question, What do you mean when you say that "Your README is unavailable for inline reviews", is that you can not see the file or anything else? What should we do in order to solve this issue?

**Comment by brytebee** [comment]
@jrosario19 & @ShingiraiBhengesa. When I tried to review it, the README was unavailable to use some review features.
That was why I dropped them in another file.

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
